[project]
name = "sentinela"
version = "0.1.0"
description = "EDR com suporte a IA local (Ollama)"
authors = [
  { name="Miguel F Araujo", email="nigelkps1@gmail.com" }
]
dependencies = [
  "fastapi",
  "uvicorn",
  "requests",
  "psutil",
  "python-nmap"
]
